### PR TITLE
Extended the Interface

### PR DESCRIPTION
**Pull request by Sparksteam**
Hi Oren - please review and consider these changes for incorporation into your master repository and package.

Added a Status flag in the resolver so clients can know if a scan is in
progress, and throw an exception if a Scan is initiated while a scan is
in progress. Added an indication of when scan is completed via the
callback. Test and handle cancelling scan more gracefully.

Thanks.

### CODE REVIEW

**Comment by onovotny** [comment]
Can we change this to be done via an alternate scan method instead of changing the implementation?

My thoughts is that there is a more reliable way of conveying the same meaning, namely by using IObservable. I suspect that the existing method can be used and the callbacks translated into OnNext calls. When the task is done, OnCompleted would be called.

I'm pretty sure this can be done with a few lightweight classes instead of pulling in Rx, which I'd prefer not to do.

Thoughts?

**Comment by Sparksteam** [comment]
Sorry Oren, what does “Rx” mean?

 

There’s certainly many ways to skin this cat. I tried to implement what I needed without further perturbation the of the ResolveAsync(),  BrowseDomainsAsync() and callback method signatures, but I hear what you’re saying. Besides using the IObservable, event subscription pattern, here a couple of more options.

 

1.       Expose a couple of events to which delegates can be assigned.

2.       Add an EventType argument to the existing callback signature.

 

What do you think?

 

Thanks.

**Comment by onovotny** [comment]
Can you please give version 2.4.1-observable01-bld013 a shot and let me know how it goes for you?

**Comment by Sparksteam** [comment]
Seems pretty well behaved Oren, although I thought some anomalies when a scan is cancelled and restarted right away. It seemed like it was discovering a couple of less devices out of 44.

 

It could just be our network:(.

**Comment by onovotny** [comment]
Closing as this was done another way. Thanks!

**Pull request closed without merging**
