### PR TITLE
New helper library and test application for UWP support.

### PR DESCRIPTION
**Pull request by queequac**
Pull request implementing #44

### CODE REVIEW

**Comment by onovotny** [comment]
Thank you for the PR. One question though -- can we accomplish the same thing by using the new/fuller Socket API's in the forthcoming System.Net.Sockets 4.1? 

Please review: 
https://github.com/dotnet/corefx/tree/master/src/System.Net.Sockets/src/System/Net/Sockets

The goal here would be to have a single `netstandard1.4` version that works everywhere (including UWP). That code would likely look virtually identical to the Desktop .NET version rather than use the WinRT API's.

**Comment by queequac** [comment]
Well, not sure how this would work.
Is that already enabled for UWP?

But aside from sockets, there is still a completely different `NetworkInformation` and `NetworkAdapter` structure, providing different (or no  😄 ) details... actually, I don't think it ends with the socket APIs and I am not sure if it is worth increasing the overall footprint for a common socket implementation if portions of the code have still to be platform-specific, even if that might be just for determining the interfaces sufficient to send queries to.

**Comment by queequac** [comment]
Just being nosy, even if `netstandard1.4` could be an option to be evaluated for the future... would you consider the additional UWP helper in the meanwhile? :smile:

**Comment by onovotny** [comment]
yeah, fair enough. I can review this and get it merged in shortly

**Pull request merged**
