### PR TITLE
Need help to make Zeroconf works with IPv6

### PR DESCRIPTION
**Pull request by tingfangzheng**
We want to run Zeroconf on Windows 7 to browse Avahi Server in Linux-OS with IPv6 setting.

We need help. Please let us know if possible, and the cost.

### CODE REVIEW

**Comment by onovotny** [comment]
I'd be happy to accept a PR that adds full IPv6 client multicast support, but it's not something I'm actively looking at right now. Most users' networks simply aren't using IPv6 right now.

**Comment by tingfangzheng** [comment]
Oren,

Glad to know you accepted this PR….

full IPv6 client multicast is important to me.

I understand it will take efforts and time.
Would you please let me know the cost, and payment method you prefer?

Thanks very much….

Ting

**Comment by onovotny** [comment]
Hi @tingfangzheng I think you misunderstand, that's not how things work with open source. To be clear, I have no plans at this time to implement IPv6 myself. If someone else, like yourself, would like to implement the feature, I'd accept that code to this project.

**Comment by tingfangzheng** [comment]
Hi Oren
  Browse with IPv6 feature is important to us, and we are lack of experience and domain knowledge.
  If possible, could you recommend some expert for us?
  Our contact information:
            tingfangzheng@gamil.com<mailto:tingfangzheng@gamil.com>
            (941) 209-8085©

**Pull request closed without merging**
